import { useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, Atom, BarChart3, Bot, BrainCircuit, Check, Code2, Database, Github, GitPullRequest, Menu, Moon, Network, Server, Settings2, Sparkles, Sun, Trophy, X } from "lucide-react";
import { GradientMeshBackground } from "@/components/effects/GradientMeshBackground";
import { MagneticButton } from "@/components/effects/MagneticButton";
import { SpotlightCard } from "@/components/effects/SpotlightCard";
import { TiltCard } from "@/components/effects/TiltCard";
import { useTheme } from "@/context/ThemeContext";

const features = [
  [Bot,"AI code review","Structured, line-aware findings powered by OpenAI."],[GitPullRequest,"Inline PR comments","Validated suggestions posted directly where developers work."],
  [BarChart3,"Code health scoring","Track severity and defect-density trends over time."],[Trophy,"Contributor leaderboard","Celebrate consistent, low-risk contributions."],
  [Settings2,"Custom rules","Teach every repository its own engineering standards."],[Sparkles,"Review personas","Choose strict, balanced, or friendly feedback."],
  [BrainCircuit,"Review memory","Chroma vector search recalls similar past findings."],[Code2,"Complexity analysis","Radon and deterministic metrics complement the LLM."]
];
const tech = [[Atom,"React"],[Server,"Node"],[Github,"GitHub"],[Database,"MongoDB"],[Bot,"OpenAI"],[Code2,"Python"]];
function Logo(){return <Link to="/" className="flex items-center gap-3"><span className="logo-mark"><i/><i/></span><b className="text-xl tracking-[-.04em]">PRism<span className="text-accent">.</span></b></Link>}
function DashboardPreview(){return <TiltCard className="mx-auto max-w-4xl p-4 sm:p-6"><div className="flex gap-3"><div className="hidden w-32 rounded-[18px] bg-surface-alt p-3 sm:block"><div className="h-7 w-20 rounded-xl bg-accent/30"/><div className="mt-8 space-y-3">{[1,2,3,4].map(i=><div key={i} className={`h-7 rounded-xl ${i===1?'bg-accent/30':'bg-surface'}`}/>)}</div></div><div className="min-w-0 flex-1"><div className="grid grid-cols-3 gap-2">{[["Reviews","1,284"],["Health","92"],["Findings","38"]].map(([a,b])=><div className="clay-card p-3" key={a}><p className="text-[9px] text-muted">{a}</p><p className="mt-1 text-lg font-extrabold">{b}</p></div>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-[1.5fr_1fr]"><div className="clay-card h-40 p-4"><p className="text-xs font-bold">Review activity</p><svg viewBox="0 0 300 100" className="mt-4 h-24 w-full"><path d="M0 80 C40 70,55 25,95 48 S155 75,185 35 S245 20,300 8" fill="none" stroke="var(--accent)" strokeWidth="5" strokeLinecap="round"/><path d="M0 80 C40 70,55 25,95 48 S155 75,185 35 S245 20,300 8 L300 100 L0 100Z" fill="var(--accent-glow)"/></svg></div><div className="clay-card h-40 p-4"><p className="text-xs font-bold">Code health</p><div className="mx-auto mt-4 grid size-20 place-items-center rounded-full border-[9px] border-accent text-xl font-extrabold">92</div></div></div></div></div></TiltCard>}
export default function Landing(){const [open,setOpen]=useState(false);const{theme,toggleTheme}=useTheme();return <div className="min-h-screen overflow-hidden bg-bg text-primary"><header className="fixed inset-x-0 top-0 z-50 border-b border-border bg-bg/80 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><Logo/><nav className="hidden items-center gap-7 text-sm font-semibold md:flex"><a href="#features">Features</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></nav><div className="hidden items-center gap-3 md:flex"><button className="clay-icon" onClick={toggleTheme} aria-label="Toggle theme">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}</button><Link to="/login" className="px-3 text-sm font-semibold">Sign in</Link><Link to="/login" className="clay-button px-5 py-3 text-sm font-bold">Get started</Link></div><button className="clay-icon md:hidden" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-border bg-bg p-5 md:hidden"><div className="flex flex-col gap-4"><a href="#features" onClick={()=>setOpen(false)}>Features</a><a href="#how" onClick={()=>setOpen(false)}>How it works</a><Link to="/login" className="clay-button py-3 text-center">Get started</Link></div></div>}</header>
<main><section className="relative px-5 pb-20 pt-36 text-center"><GradientMeshBackground/><div className="relative mx-auto max-w-5xl"><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="clay-badge inline-flex items-center gap-2"><Sparkles size={14}/> AI review that remembers</motion.div><h1 className="mx-auto mt-7 max-w-4xl text-5xl font-black tracking-[-.06em] sm:text-7xl">Ship better code with every pull request.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-muted sm:text-lg">PRism blends AI review, vector memory, and deterministic complexity analysis into clear feedback your team can trust.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><Link to="/login"><MagneticButton>Start reviewing <ArrowRight size={17}/></MagneticButton></Link><a href="https://github.com/Vanshika17-05/PRism" target="_blank" rel="noreferrer" className="clay-control inline-flex h-11 items-center gap-2 px-5 text-sm font-bold"><Github size={17}/> View source</a></div><div className="mt-16"><DashboardPreview/></div></div></section>
<section className="border-y border-border py-8"><p className="text-center text-xs font-bold uppercase tracking-[.2em] text-muted">Built with a production-minded stack</p><div className="mx-auto mt-5 flex max-w-4xl flex-wrap justify-center gap-7">{tech.map(([Icon,name])=><span key={name} className="flex items-center gap-2 font-semibold text-muted"><Icon size={20} className="text-accent"/>{name}</span>)}</div></section>
<section id="features" className="mx-auto max-w-7xl px-5 py-24"><div className="mx-auto max-w-2xl text-center"><p className="font-bold text-accent-dark">ENGINEERING SIGNAL, NOT NOISE</p><h2 className="mt-3 text-4xl font-black tracking-tight">One reviewer. Eight superpowers.</h2></div><motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={{show:{transition:{staggerChildren:.05}}}} className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,text])=><motion.div variants={{hidden:{opacity:0,y:12},show:{opacity:1,y:0}}} key={title}><SpotlightCard className="h-full p-6"><span className="clay-icon text-accent-dark"><Icon size={19}/></span><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{text}</p></SpotlightCard></motion.div>)}</motion.div></section>
<section id="how" className="bg-surface-clay/40 px-5 py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="font-bold text-accent-dark">HOW IT WORKS</p><h2 className="mt-3 text-4xl font-black">From webhook to wisdom.</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[[GitPullRequest,"1","A pull request changes"],[Network,"2","PRism analyzes and remembers"],[Check,"3","Findings land on GitHub"]].map(([Icon,n,t])=><div className="clay-card p-7 text-center" key={n}><span className="mx-auto grid size-14 place-items-center rounded-[20px] bg-accent text-xl font-black text-[#052B26]">{n}</span><Icon className="mx-auto mt-6 text-accent"/><h3 className="mt-4 font-extrabold">{t}</h3></div>)}</div></div></section>
<section className="mx-auto grid max-w-6xl gap-10 px-5 py-24 lg:grid-cols-2 lg:items-center"><div><p className="font-bold text-accent-dark">REAL REVIEW OUTPUT</p><h2 className="mt-3 text-4xl font-black tracking-tight">Specific enough to fix. Calm enough to trust.</h2><p className="mt-5 leading-7 text-muted">Every inline comment is verified against a real changed line before PRism sends it to GitHub.</p></div><SpotlightCard className="p-6"><div className="flex items-center gap-3"><span className="size-3 rounded-full bg-high"/><span className="clay-badge">HIGH · SECURITY</span><span className="ml-auto font-mono text-xs text-muted">auth.js:42</span></div><h3 className="mt-5 font-extrabold">Authorization check can be bypassed</h3><p className="mt-3 text-sm leading-6 text-muted">The service-token fallback accepts a decoded token without validating its audience, allowing a token minted for another service.</p><pre className="mt-4 overflow-auto rounded-[18px] bg-[#071411] p-4 text-xs text-[#9DF5E8]"><code>if (payload.aud !== env.AUTH_AUDIENCE) throw new UnauthorizedError();</code></pre><div className="mt-4 flex gap-3 text-xs text-muted"><span>96% confidence</span><span>·</span><span>Similar to PR #12</span></div></SpotlightCard></section>
<section id="pricing" className="px-5 pb-24"><div className="clay-card relative mx-auto max-w-5xl overflow-hidden p-10 text-center sm:p-16"><GradientMeshBackground/><div className="relative"><h2 className="text-4xl font-black">Make every review compound.</h2><p className="mx-auto mt-4 max-w-xl text-muted">Run locally in mock mode today, then connect MongoDB, GitHub, and OpenAI when your team is ready.</p><Link to="/login" className="clay-button mt-8 inline-flex items-center gap-2 px-6 py-3 font-bold">Open your workspace <ArrowRight size={17}/></Link></div></div></section></main>
<footer className="border-t border-border px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-sm text-muted sm:flex-row"><Logo/><p>Built by Vanshika Sambher · {new Date().getFullYear()}</p><a href="https://github.com/Vanshika17-05/PRism" target="_blank" rel="noreferrer" className="flex items-center gap-2"><Github size={16}/> GitHub</a></div></footer></div>}
