import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { ArrowLeft, Eye, EyeOff, LogIn, Moon, Sparkles, Sun } from "lucide-react";
import { toast } from "sonner";
import { GradientMeshBackground } from "@/components/effects/GradientMeshBackground";
import { MagneticButton } from "@/components/effects/MagneticButton";
import { useAuth } from "@/context/AuthContext";
import { useTheme } from "@/context/ThemeContext";

export default function Login(){const[email,setEmail]=useState("demo@prism.dev");const[password,setPassword]=useState("prism-demo-2026");const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const{login}=useAuth();const{theme,toggleTheme}=useTheme();const navigate=useNavigate();const location=useLocation();async function submit(e){e.preventDefault();setBusy(true);try{await login({email,password});toast.success("Welcome to PRism");navigate(location.state?.from||"/dashboard/overview",{replace:true})}catch(error){toast.error(error.message)}finally{setBusy(false)}}return <div className="relative grid min-h-screen place-items-center overflow-hidden bg-bg px-5 py-16 text-primary"><GradientMeshBackground/><Link to="/" className="absolute left-5 top-5 flex items-center gap-2 text-sm font-semibold text-muted"><ArrowLeft size={17}/> Back home</Link><button className="clay-icon absolute right-5 top-5" onClick={toggleTheme} aria-label="Toggle theme">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}</button><form onSubmit={submit} className="clay-card relative z-10 w-full max-w-md p-7 sm:p-9"><div className="flex items-center gap-3"><span className="logo-mark"><i/><i/></span><div><h1 className="text-2xl font-black">Welcome back</h1><p className="text-sm text-muted">Sign in to your review workspace</p></div></div><label className="mt-8 block text-sm font-bold">Email<input className="clay-input mt-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label className="mt-5 block text-sm font-bold">Password<div className="relative mt-2"><input className="clay-input pr-12" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button type="button" className="absolute right-3 top-3 text-muted" onClick={()=>setShow(!show)} aria-label="Show password">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><MagneticButton className="mt-7 w-full" disabled={busy}>{busy?'Signing in…':<>Sign in <LogIn size={17}/></>}</MagneticButton><div className="mt-6 rounded-[18px] border border-border bg-surface-alt p-4 text-xs leading-5 text-muted"><p className="flex items-center gap-2 font-bold text-primary"><Sparkles size={14} className="text-accent"/> Demo access</p><p className="mt-1">Credentials are prefilled. Mock mode keeps the full dashboard usable without external services.</p></div></form></div>}
